{"_default": {"1": {"app_name": "pwho", "docker_image": "hello-world", "dashboard_url": "/dashboard/pwho", "app_url": "pwho.divyasheel.com", "user_id": "admin"}}, "instances": {"1": {"provisioned": false, "provisioning": false, "docker_image": "hello-world", "user_id": "admin", "machine_url": "http://192.168.196.125", "error": "HTTPConnectionPool(host='192.168.196.125', port=8080): Max retries exceeded with url: /build-from-hub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0e4190fa0>: Failed to establish a new connection: [Errno 111] Connection refused'))"}, "2": {"provisioned": false, "provisioning": false, "docker_image": "hello-world", "user_id": "admin", "machine_url": "http://192.168.196.125", "error": "HTTPConnectionPool(host='192.168.196.125', port=8080): Max retries exceeded with url: /build-from-hub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0e4190610>: Failed to establish a new connection: [Errno 111] Connection refused'))"}, "3": {"provisioned": true, "provisioning": false, "docker_image": "hello-world", "user_id": "admin", "machine_url": "http://192.168.196.27", "instance_url": "http://192.168.196.27:50547"}, "4": {"provisioned": false, "provisioning": false, "docker_image": "hello-world", "user_id": "admin", "machine_url": "http://192.168.196.125", "error": "HTTPConnectionPool(host='192.168.196.125', port=8080): Max retries exceeded with url: /build-from-hub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe0e4190610>: Failed to establish a new connection: [Errno 111] Connection refused'))"}, "5": {"provisioned": true, "provisioning": false, "docker_image": "hello-world", "user_id": "admin", "machine_url": "http://192.168.196.27", "instance_url": "http://192.168.196.27:54009"}}}